services:
  db:
    image: mysql:8.4
    container_name: lasan_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "38217:3306"

  wordpress:
    image: wordpress:latest
    container_name: lasan_wp
    restart: unless-stopped
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - .:/var/www/html
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    ports:
      - "49731:80"

volumes:
  db_data:
